nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        # allow_credentials: true
        #         origin_regex: false
        #         allow_origin: ['*']
        #         allow_headers: ['Origin','Accept','Content-Type']
        #         allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
        #         max_age: 3600
